# Production Docker Compose Configuration
# Uses pre-built images from Docker Hub

services:
  backend:
    image: xiebaiyuan/who-block-your-dns:backend-v1.20250826.14
    container_name: adguard-backend
    restart: unless-stopped
    ports:
      - "49225:8080"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - /share/ssd/adguard-dns-query/app/logs:/app/logs
    networks:
      - adguard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/rules/statistics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: xiebaiyuan/who-block-your-dns:frontend-v1.20250826.14
    container_name: adguard-frontend
    restart: unless-stopped
    ports:
      - "49226:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - adguard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_logs:
    driver: local

networks:
  adguard-network:
    driver: bridge