version: "3.8"

services:
  backend:
    image: xiebaiyuan/who-block-you:backend-v1.20250827.17
    container_name: adguard-backend
    restart: unless-stopped
    ports:
      - "49225:8080"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # 代理配置(可选)
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-}
    volumes:
      - /share/ssd/adguard-dns-query/app/logs:/app/logs
    # 移除 network_mode: bridge

  frontend:
    image: xiebaiyuan/who-block-you:frontend-v1.20250827.17
    container_name: adguard-frontend
    restart: unless-stopped
    ports:
      - "49226:80"
    environment:
      - BACKEND_URL=http://backend:8080
    # 移除 network_mode: bridge
    depends_on:
      - backend