version: "3.8"

services:
  backend:
    image: xiebaiyuan/who-block-you:backend-v1.20250827.19
    container_name: adguard-backend
    restart: unless-stopped
    ports:
      - "49225:8080"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RULES_DIR=/app/data/rules
      - RULE_SOURCES_CONFIG_FILE=${RULE_SOURCES_CONFIG_FILE:-/app/data/rule_sources.json}
      # 代理配置(可选)
      - HTTP_PROXY=http://xxx:1080
      - HTTPS_PROXY=http://xxx:1080
      - NO_PROXY=12.0.0.0/8,localhost,127.0.0.1
    volumes:
      - /share/ssd/adguard-dns-query/app/logs:/app/logs
      # Persist downloaded rule files so they can be inspected
      - /share/ssd/adguard-dns-query/app/rules:/app/data/rules
    networks:
      - whoblocku-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/rules/statistics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: xiebaiyuan/who-block-you:frontend-v1.20250827.19
    container_name: adguard-frontend
    restart: unless-stopped
    ports:
      - "49226:80"
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - whoblocku-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  whoblocku-network:
    driver: bridge